#!/bin/bash

ARCHIVE=~/journal/archive

echo "+ removing empty/unused directories"
find $ARCHIVE -mindepth 1 -depth -type d -empty -delete

echo "+ setting old files to readonly"
find $ARCHIVE -type f -exec chmod u-w {} \;
find $ARCHIVE -type d -mindepth 1 -exec chmod u-w {} \;

echo "+ creating archive directory for today"
DST=$ARCHIVE/`date "+%Y-%m-%d"`
if [ ! -d $DST ] ; then
    mkdir $DST
else # if this was already created for some reason, reset the directory's permissions
    chmod u+w $DST
fi
